### ISSUE TITLE
Failed to initialize logging driver: dial udp when provisioning the DOA stack

### ISSUE THREAD

**Issue by RobertNorthard** [dsingh07/adop-doa-materials#2]
I am intermittently getting the following error when provisioning a new DOA stack. Please see the cloud-init log extract below.

`
Bringing up ADOP...
Sourcing provider-specific environment files...
Sourcing ./conf/provider/env.provider.aws.sh parameters file...
Your secrets file already exists, will not re-create...
Sourcing variables from platform.secrets.sh file...
The version of your secrets file is up to date, moving on...
Creating logstash
Creating elasticsearch
Creating kibana
The DOCKER_TLS_VERIFY variable is not set. Defaulting to a blank string.
Creating ldap-ltb
Creating sonar-mysql
Creating nexus
Creating sensu-redis
Creating sensu-rabbitmq
Creating ldap
Creating ldap-phpadmin
Creating jenkins
Creating gerrit
Creating selenium-node-firefox
Creating proxy
Creating selenium-node-chrome
Creating sensu-uchiwa
Creating sensu-server
Creating sonar
Creating gerrit-mysql
Creating selenium-hub
Creating sensu-client
Creating jenkins-slave
Creating sensu-api
ERROR: for selenium-node-chrome  Failed to initialize logging driver: dial udp 54.199.155.255:25826: connect: network is unreachable
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
docker-compose returned -1
2016-11-09 13:26:13,425 - util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [255]
2016-11-09 13:26:13,433 - cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
2016-11-09 13:26:13,434 - util.py[WARNING]: Running scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed`

**Comment by dsingh07** [comment]
Hi @RobertNorthard 

At a first glance, this seems like an intermittent network issue. The security group has been opened up by default for port 25826 on UDP so I would expect it to not have any issues initializing the logging driver. It's strange that it happens just for selenium-node-chrome.

Does the stack fail complete creation with the wait condition timing out when you encounter the above issue?

**Comment by RobertNorthard** [comment]
I agree - I couldn't diagnose why it was just the selenium log driver. When I ran `$ adop compose init`  on the box manually it worked as expected before the stack creation timed out and it was destroyed.

**Comment by RobertNorthard** [comment]
Closing as I am no longer getting this issue.
